project_name: kube-echo
builds:
  - <<: &build_defaults
      binary: kube-echo
      main: main.go
      ldflags:
        - -s -w -X main.VERSION={{ .Version }}
      env:
        - CGO_ENABLED=0
    id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
  - <<: *build_defaults
    id: windows
    goos:
      - windows
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    id: all
    rlcp: true
    builds: [windows, linux, darwin]
    format: tar.gz
    files:
      - none*
dockers:
  - image_templates:
      - 'ghcr.io/piontec/kube-echo:{{ .Tag }}-amd64'
      - 'ghcr.io/piontec/kube-echo:latest-amd64'
    dockerfile: Dockerfile
    use: buildx
      #  goos: linux
      #  goarch: amd64
    build_flag_templates:
      - "--pull" 
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/amd64"
  - image_templates:
      - 'ghcr.io/piontec/kube-echo:{{ .Tag }}-arm64'
      - 'ghcr.io/piontec/kube-echo:latest-arm64'
    dockerfile: Dockerfile
    use: buildx
      #  goos: linux
      #  goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/arm64"
  - image_templates:
      - 'ghcr.io/piontec/kube-echo:{{ .Tag }}-arm'
      - 'ghcr.io/piontec/kube-echo:latest-arm'
    dockerfile: Dockerfile
    use: buildx
      #  goos: linux
      #  goarch: arm
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/arm"
docker_manifests:
  - name_template: 'ghcr.io/piontec/kube-echo:{{ .Tag }}'
    image_templates:
      - 'ghcr.io/piontec/kube-echo:{{ .Tag }}-amd64'
      - 'ghcr.io/piontec/kube-echo:{{ .Tag }}-arm64'
      - 'ghcr.io/piontec/kube-echo:{{ .Tag }}-arm'
  - name_template: 'ghcr.io/piontec/kube-echo:latest'
    image_templates:
      - 'ghcr.io/piontec/kube-echo:latest-amd64'
      - 'ghcr.io/piontec/kube-echo:latest-arm64'
      - 'ghcr.io/piontec/kube-echo:latest-arm'
docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - sign
      - "--yes"
      - '${artifact}'
    artifacts: all
    output: true
source:
  enabled: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_src'
sboms:
  - artifacts: archive
  - id: source
    artifacts: source
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_sbom.spdx.json"
release: {}
checksum: {}
signs:
  - cmd: cosign
    env:
    - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - "--yes"
    artifacts: checksum
    output: true
changelog:
  use: github
  skip: true
